//public class SalesforceDeveloper {
   // public void myFirstCode(){
        //string myFavoriteCity='New York';
       // system.debug(myFavoriteCity);
        
       // string myfavoriteMovie='Avatar';
        //system.debug(myfavoriteMovie);

        //string myFavoriteSeason='Spring and Summer';
        //system.debug(myFavoriteSeason);


    //}
   public class SalesforceDeveloper{

    public void myFavorities(){
        string sehir = 'Seattle';
        system.debug(sehir);

        integer numara = 17;
        system.debug(numara);

        system.debug( 'Benim sevdigim Sehir -->'  +  ' ' + sehir + ' ' +  'En Sevdigim Numara -->'  +  numara);

    }

   }

   
    

